# 1D lattice

[chain_p]

dimension = 1

[chain_p.C1]
space_groups = [1]

[chain_p.Cs]
space_groups = [2]

# 5 2D lattices and the corresponding possible point groups

[oblique_p]

dimension = 2

[oblique_p.C1]
space_groups = [1]

[oblique_p.C2]
space_groups = [2]



[rectangular_p]

dimension = 2

[rectangular_p.Cs]
space_groups = [3,4]

[rectangular_p.C2v]
space_groups = [6,7,8]


[rectangular_c]

dimension = 2

[rectangular_c.Cs]
space_groups = [5]

[rectangular_c.C2v]
space_groups = [9]



[square_p]

dimension = 2

[square_p.C4]
space_groups = [10]

[square_p.C4v]
space_groups = [11,12]



[hexagonal_p]

dimension = 2

[hexagonal_p.C3]
space_groups = [13]

[hexagonal_p.C3v]
space_groups = [14,15]

[hexagonal_p.C6]
space_groups = [16]

[hexagonal_p.C6v]
space_groups = [17]


# 14 Bravais lattices and corresponding possible point groups

[Triclinic_P]

dimension = 3

[Triclinic_P.C1]
space_groups = [1]

[Triclinic_P.Ci]
space_groups = [2]



[Monoclinic_P]

dimension = 3

[Monoclinic_P.C2]
space_groups = [3,4]

[Monoclinic_P.Cs]
space_groups = [6,7]

[Monoclinic_P.C2h]
space_groups = [10,11,13,14]


[Monoclinic_B]

dimension = 3

[Monoclinic_B.C2]
space_groups = [5]

[Monoclinic_B.Cs]
space_groups = [8,9]

[Monoclinic_B.C2h]
space_groups = [12,15]



[Orthorombic_P]

dimension = 3

[Orthorombic_P.D2]
space_groups = [16,17,18,19]

[Orthorombic_P.C2v]
space_groups = [25,26,27,28,29,30,31,32,33,34]

[Orthorombic_P.D2h]
space_groups = [47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62]


[Orthorombic_C]

dimension = 3

[Orthorombic_C.D2]
space_groups = [20,21]

[Orthorombic_C.C2v]
space_groups = [35,36,37]

[Orthorombic_C.D2h]
space_groups = [63,64,65,66,67,68]


[Orthorombic_F]

dimension = 3

[Orthorombic_F.D2]
space_groups = [22]

[Orthorombic_F.C2v]
space_groups = [42,43]

[Orthorombic_F.D2h]
space_groups = [69,70]


[Orthorombic_I]

dimension = 3

[Orthorombic_I.D2]
space_groups = [23,24]

[Orthorombic_I.C2v]
space_groups = [44,45,46]

[Orthorombic_I.D2h]
space_groups = [71,72,73,74]


[Orthorombic_A]

dimension = 3

[Orthorombic_A.C2v]
space_groups = [38,39,40,41]



[Tetragonal_P]

dimension = 3

[Tetragonal_P.C4]
space_groups = [75,76,77,78]

[Tetragonal_P.S4]
space_groups = [81]

[Tetragonal_P.C4h]
space_groups = [83,84,85,86]

[Tetragonal_P.D4]
space_groups = [89,90,91,92,93,94,95,96]

[Tetragonal_P.C4v]
space_groups = [99,100,101,102,103,104,105,106]

[Tetragonal_P.D2d]
space_groups = [111,112,113,114,115,116,117,118]

[Tetragonal_P.D4h]
space_groups = [123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138]


[Tetragonal_I]

dimension = 3

[Tetragonal_I.C4]
space_groups = [79,80]

[Tetragonal_I.S4]
space_groups = [82]

[Tetragonal_I.C4h]
space_groups = [87,88]

[Tetragonal_I.D4]
space_groups = [97,98]

[Tetragonal_I.C4v]
space_groups = [107,108,109,110]

[Tetragonal_I.D2d]
space_groups = [119,120,121,122]

[Tetragonal_I.D4h]
space_groups = [139,140,141,142]



[Trigonal_P]

dimension = 3

[Trigonal_P.C3]
space_groups = [143,144,145]

[Trigonal_P.C3i]
space_groups = [147]

[Trigonal_P.D3]
space_groups = [149,150,151,152,153,154]

[Trigonal_P.C3v]
space_groups = [156,157,158,159]

[Trigonal_P.D3d]
space_groups = [162,163,164,165]


[Trigonal_R]

dimension = 3

[Trigonal_R.C3]
space_groups = [146]

[Trigonal_R.C3i]
space_groups = [148]

[Trigonal_R.D3]
space_groups = [155]

[Trigonal_R.C3v]
space_groups = [160,161]

[Trigonal_R.D3d]
space_groups = [166,167]



[Hexagonal_P]

dimension = 3

[Hexagonal_P.C6]

space_groups = [168,169,170,171,172,173]

[Hexagonal_P.C3h]

space_groups = [174]

[Hexagonal_P.C6h]

space_groups = [175,176]

[Hexagonal_P.D6]

space_groups = [177,178,179,180,181,182]

[Hexagonal_P.C6v]

space_groups = [183,184,185,186]

[Hexagonal_P.D3h]

space_groups = [187,188,189,190]

[Hexagonal_P.D6h]

space_groups = [191,192,193,194]



[Cubic_P]

dimension = 3

[Cubic_P.T]
space_groups = [195,198]

[Cubic_P.Th]
space_groups = [200,201,205]

[Cubic_P.O]
space_groups = [207,208,212,213]

[Cubic_P.Td]
space_groups = [215,218]

[Cubic_P.Oh]
space_groups = [221,222,223,224]


[Cubic_F]

dimension = 3

[Cubic_F.T]
space_groups = [196]

[Cubic_F.Th]
space_groups = [202,203]

[Cubic_F.O]
space_groups = [209,210]

[Cubic_F.Td]
space_groups = [216,219]

[Cubic_F.Oh]
space_groups = [225,226,227,228]


[Cubic_I]

dimension = 3

[Cubic_I.T]
space_groups = [197,199]

[Cubic_I.Th]
space_groups = [204,206]

[Cubic_I.O]
space_groups = [211,214]

[Cubic_I.Td]
space_groups = [217,220]

[Cubic_I.Oh]
space_groups = [229,230]



