#! /usr/bin/env python3
# Andrey Zelenskiy, 2024

"""
=================
particle_utils.py
=================

This submodule provides tools to create a Particle object with specified face
coloring.
"""

import numpy as np
from samosa.api.api_utils import array_type, NoneType, is_None, not_None
from samosa.api.api_utils import check_type, check_len, check_shape, check_ifdef

from samosa.symmetry.group_utils import Group
from samosa.symmetry.point_group_utils import point_group
"""
-------------------------------------------------------------------------------
Particle class
-------------------------------------------------------------------------------
"""
class Particle:
    """
    Defines an anisotropic particle object.

    A particle is characterized by its topology and geometry.

    Topological propertie:
    - Number of faces;
    - Particle symmetry (if given);
    - Face coloring (if given);

    Geometric properties:
    - Space and particle face point group (determines the generic shape of the
      particle);
    - Spatial coordinates of particle faces;
    - Positions of patches on the particle (if given).


    """

    def __init__(self, particle_symmetry = None, coloring_symmetry = None,
                       n_faces = None, face_coloring = None):
        """
        Initialize a Particle object.

        Optional arguments (default = None):
        particle_symmetry - Group or str, point group that generates all 
                            permutations of particle faces:
                            if Group, initializes the point group directly from
                            input (generators must represented as permutations
                            of particle faces and be of PermutationGroupElement
                            type);
                            if str, specifies the Schoenflies symbol of the 
                            point group (requires specification of 
                            face_coordinates);
        coloring_symmetry - Group or str, point group generated by 
                            transformations that leave particle face labels 
                            unchanged;
                            if Group, initializes the point group directly from
                            input (generators must represented as permutations
                            of particle faces and be of PermutationGroupElement
                            type);
                            if str, specifies the Schoenflies symbol of the 
                            point group (requires specification of 
                            face_coordinates);
        n_faces           - int, total number of particle faces;
        face_coloring     - array_type of ints, color labels of particle faces.
        """

        self.particle_symmetry = particle_symmetry
        self.coloring_symmetry = coloring_symmetry 
        self.n_faces = n_faces
        self.face_coloring = face_coloring
    
    # Topological properties

    ## Total number of particle faces
    @property
    def n_faces(self):
        if is_None(self.__n_faces):
            print("Number of particle faces is not set.")

        return self.__n_faces


    @n_faces.setter
    def n_faces(self, val, overwrite = False):
        # Type check
        check_type('n_faces',val,NoneType,int)
        
        # Value assignment
        self.__n_faces = val


    @n_faces.deleter
    def n_faces(self):
        self.__n_faces = None


    ## Color labels of particle faces 
    @property
    def face_coloring(self):
        if is_None(self.__face_coloring):
            print("Face color labels are not set.")

        return self.__face_coloring


    @face_coloring.setter
    def face_coloring(self, val):
        # Type checks
        check_type('face_coloring',val,NoneType,array_type)
        if not_None(val):
            for v in val:
                check_type('face_coloring elements',v,int)
       
            # Compatibility check
            if not_None(self.n_faces):
                check_len('face_coloring',val,self.n_faces)
            else: 
                self.n_faces = len(val)

            val = np.array(val)

        # Value assignment
        self.__face_coloring = val


    @face_coloring.deleter
    def face_coloring(self):
        self.__face_coloring = None


    ## Point group symmetry of the particle
    @property
    def particle_symmetry(self):
        if is_None(self.__particle_symmetry):
            print("Particle symmetry is not set.")

        return self.__particle_symmetry


    @particle_symmetry.setter
    def particle_symmetry(self, val):
        # Type checks
        check_type('particle_symmetry',val,NoneType,Group,str)

        if isinstance(val,str):
            val = point_group(val)
            


    @particle_symmetry.deleter
    def particle_symmetry(self):
        self.__particle_symmetry = None



    ## Symmetry group that leaves particle coloring unchanged
    @property
    def coloring_symmetry(self):
        pass


    # Geometric properties

    @property
    def face_coordinates(self):
        pass

    @property
    def vertex_coordinates(self):
        pass


    def _print_property(self, val_name, val):
        """
        String output for class properties.
        """
        if is_None(val):
            return f"{val_name} is not set\n"
        else:
            return f"{val_name} = {str(val)}\n"


    def __str__(self):
        """
        User-friendly summary of the object's properties.
        """

        return "Particle object:\n"\
             + self._print_property('particle_symmetry',self.particle_symmetry)\
             + self._print_property('coloring_symmetry',self.coloring_symmetry)\
             + self._print_property('n_faces',self.n_faces)\
             + self._print_property('face_coloring',self.face_coloring)
