# List of generators of the 32 crystallographic point groups

## Triclinic
[C1]
generators = ["E,000"]

[Ci]
generators = ["I,000"]


## Monoclinic
[C2]
generators = ["C2,001"]

[Cs]
generators = ["m,001"]

[C2h]
generators = ["C2,001","I,000"]


## Orthorhombic
[D2]
generators = ["C2,010","C2,001"]

[C2v]
generators = ["C2,001","m,010"]

[D2h]
generators = ["C2,010","C2,001","I,000"]


## Tetragonal
[C4]
generators = ["C4p,001"]

[S4]
generators = ["S4p,001"]

[C4h]
generators = ["C4p,001","I,000"]

[D4]
generators = ["C4p,001","C2,010","C2,001"]

[C4v]
generators = ["C4p,001","C2,001","m,010"]

[D2d]
generators = ["S4p,001","C2,010","C2,001"]

[D4h]
generators = ["C4p,001","C2,010","C2,001","I,000"]


## Trigonal
[C3]
generators = ["C3p,001"]

[C3i]
generators = ["S3p,001"]

[D3]
generators = ["C3p,001","C2,1-10"]

[C3v]
generators = ["C3p,001","m,110"]

[D3d]
generators = ["S6p,001","C2,1-10","I,000"]


## Hexagonal
[C6]
generators = ["C6p_H,001"]

[C3h]
generators = ["C3p_H,001","I,000"]

[C6h]
generators = ["C6p_H,001","I,000"]

[D6]
generators = ["C3p_H,001","C2,001","C2,110"]

[C6v]
generators = ["C3p_H,001","C2,001","m,110"]

[D3h]
generators = ["C3p_H,001","C2,1-10","m,001"]

[D6h]
generators = ["C3p_H,001","C2,001","C2,110","I,000"]


## Cubic
[T]
generators = ["C3p,111","C2,010","C2,001"]

[Th]
generators = ["C3p,111","C2,010","C2,001","I,000"]

[O]
generators = ["C3p,111","C2,010","C2,110","C2,001"]

[Td]
generators = ["C3p,111","C2,010","C2,001","m,1-10"]

[Oh]
generators = ["C3p,111","C2,010","C2,110","C2,001","I,000"]
