#! /usr/bin/env python3
# Andrey Zelenskiy, 2024

"""
=================
symmetry_utils.py
=================

This script defines the `group` object, which contains all of the necessary 
information and methods for symmetry analysis.
"""

import numpy as np
import warnings

def custom_formatwarning(msg, *args, **kwargs):
    """
    When throwing a warning, only throw the message
    """
    return str(msg) + '\n'

warnings.formatwarning = custom_formatwarning

"""
-------------------------------------------------------------------------------
Group class
-------------------------------------------------------------------------------
"""
class Group:
    """
    A container for storing the properties and methods of a symmetry group. 
    """

    def __init__(self, generators):
        """
        Defines the group generators.
        """

        self.generators = generators


    # Routines for orbit/stabilizers calculations

    def stabilizer_generator_filter(stabilizer, stabilizer_list, blacklist):
        """
        Determines whether a stabilizing operation qualifies as a new generator
        of the stabilizer group. 
    
        Arguments:
        stabilizer      - np.2darray, stabilizer matrix;
        stabilizer_list - list of np.2darray, list of known generators of the
                          stabilizer group;
        blacklist       - list of np.2darray, list of operators related to the
                          known generators of the stabilizer group.

        Returns:
        Either the original, or the updated stabilizer_list, blacklist.
        """

        # Check if the stabilizer is already in the stabilizer list
        if not array_in_list(stabilizer, stabilizer_list):

            # Check if the stabilizer is related to the known generators
            if not array_in_list(stabilizer, blacklist):  

                # Both tests are passed, update stabilizer_list and blacklist  
                extended_stabilizer = [np.eye(3,dtype=int)] + stabilizer_list

                for s in extended_stabilizer:
                    g_head = s.dot(stabilizer)
                    g_chain = g_head
                    while not array_in_list(g_chain, blacklist):
                        blacklist += [g_chain]
                        g_chain = g_chain.dot(g_head)

                stabilizer_list += [stabilizer]

        return stabilizer_list, blacklist         

    def calculate_orbit(self, p0, as_pointer = True):
        """
        Calculates the orbit of a single point under the action of the group. 

        When a group element is applied to a seed point (p0), it either generates
        a new point or leaves the seed unchanged. The set of all points 
        generated by applying all group elements to the seed is called the 
        orbit of the seed point.

        The following algorithm allows one to calculate the orbit, transporters
        (group elements that transform the seed into other points in the orbit),
        and stabilizers (group elements that transform the seed into itself).

        To save memory, transporters and stabilizers may be stored as pointers
        to the sequence of generators that produce the correct group element. 
        For example, if the generator set is {g1,g2}, and element g3 transforms 
        the seed point p0 to point p1, i.e.

        g3 * p0 = p1,

        where 

        g3 = g1 * g2 * g2 
           = generators[0] * generators[1] * generators[1],

        we may represent g3 as a pointer

        g3_pointer = [0,1,1].

        The option to output group elements as pointers is controlled by 
        as_pointer argument.

        Note that the set of all stabilizers of the seed comprises a group 
        (called the stabilizer group). The list of stabilizers in the output
        of this program will contain the generators of the stabilizer group,
        but will have redundant elements (i.e. not a miniomal generating set).
        Afterwards, one can use the generator_filter routine to obtaine the 
        minimal generating set.


        Arguments:
        p0         - array_type with rank equal to the rank of the group 
                     elements, the 'seed' point of the orbit;
        as_pointer - bool, (optional, default = True), when True, outputes the
                     group elements as pointers to the generating set.

        Returns:
        output           - list, which, depending on options, contains:
        orbit            - list of np.ndarray, a closed set of points generated
                           from the seed  through application of group elements;
        transporter_dict - dict tuple:list (as_pointer = True) or 
                           dict tuple:GroupElement_type (as_pointer = False),
                           a set of group operators (values) that transform the
                           seed to other points in the orbit (keys);
        stabilizer_list  - list of lists (as_pointer = True) or
                           list of GroupElement_type (as_pointer = False),
                           operators that leave the seed point unchanged.
        """

        orbit = [p0]

        if as_pointer:
            eye_element = PointerGroupElement([],
                                              generator_list=self.generators)
            transporter_dict = {tuple(p0):eye_element}
            stabilizer_list  = [eye_element]

        else:
            matrix_rank = self.generators[0].rank
            eye_element = MatrixGroupElement(np.eye(matrix_rank),
                                             store_inverse = True, 
                                             operator_inv = np.eye(matrix_rank))
            transporter_dict = {tuple(p0):eye_element}
            stabilizer_list = [eye_element]

        for p in orbit:
            print(p)
            for ind_g, g in enumerate(self.generators):
                q = g*p

                if not array_in_list(q, orbit):
                    orbit += [q]

                    if as_pointer:
                        transporter_dict[tuple(q)] = \
                                (ind_g,1)*transporter_dict[tuple(p)]

                    else:
                        transporter_dict[tuple(q)] = \
                                g*transporter_dict[tuple(p)]

                else:
                    """
                    We assume that some group generator g satisfies

                    g_21 p_1 = p_2

                    where p and q are points in the orbit of a known seed point
                    p_0. Assuming that

                    p_1 = g_10 p_0
                    p_2 = g_20 p_0

                    where operators g_10 and g_20 are known, we can obtain two
                    stabilizer operations as

                    s_1 = g_20^-1 g_21 g_10
                    s_2 = g_10^-1 g_21^-1 g_20 = s_1^-1

                    Since we are interested in generators, we only need s_1.
                    """

                    g_10 = transporter_dict[tuple(p)]
                    g_20 = transporter_dict[tuple(q)]
                    g_20_inv = g_20.inv()
                    
                    if as_pointer:
                        stabilizer = g_20_inv*(ind_g,1)*g_10
                    else:
                        stabilizer = g_20_inv*g*g_10

                    if not element_in_list(stabilizer, stabilizer_list):
                        stabilizer_list += [stabilizer]

        return orbit, transporter_dict, stabilizer_list

    def __str__(self):
        """
        Provides user-friendly summary of the group container.
        """

        generators_str = "\n".join([str(g) for g in self.generators])

        summary_string = 'Symmetry group defined by generators:\n'\
                + generators_str

        return summary_string

    def __repr__(self):
        """
        Provedes useful print output.
        """
        cls = self.__class__.__name__
        return f"{cls}(generators = {self.generators!r})"





def as_permutation(a_list, matrix_operator):
    """
    Transforms a matrix operator into a cycle/permutation basis using a closed
    set of points.

    Arguments:
    a_list          - list of np.1darray, a set of points, which defines the
                      space of permutations;
    matrix_operator - np.2darray, a symmetry operator acting on the points in 
                      the a_list.

    Returns:
    permutation_operator - tuple of size len(a_list), permutation 
                           representation of the matrix_operator.
    """

    # Construct a hash map for the points in the a_list  
    dict_keys = [tuple(p) for p in a_list]
    dict_vals = [i for i in range(len(a_list))]
    index = dict(zip(dict_keys,dict_vals))

    try:
        permutation_operator = [index[tuple(matrix_operator.dot(p))] \
                for p in a_list]

    except KeyError:
        raise ValueError("Cannot determine the permutation representation: "\
                         "list of points is not a closed set")


    return permutation_operator


"""
-------------------------------------------------------------------------------
Interface for group elements representation
-------------------------------------------------------------------------------
"""

class GroupElement():
    """
    Interface class for a group element object.
    """

    def __mul__(self, element):
        """
        Left group element multiplication and group action.
        """
        pass

    def __rmul__(self, element):
        """
        Right group element multiplication and group action.
        """
        pass

    def inv(self):
        """
        Group element inverse.
        """
        pass 

    def __eq__(self, element):
        """
        Group element comparison.
        """
        pass

    def __str__(self):
        """
        User-friendly output.
        """
        pass


"""
-------------------------------------------------------------------------------
Generator pointer representation of group elements
-------------------------------------------------------------------------------
"""

class PointerGroupElement(GroupElement):
    """
    Translates group element properties (element multiplication, inverse) to
    pointer representation of the group elements.


    In the pointer representation a specified group element is represented 
    as a list of integers that correspond to the sequence of generators that 
    produce the specified group element. For example, if the generator set is 
    
    generator_list = {g1,g2}, 

    and some other group element g3 can be written as  

    g3 = g1 * g2 * g2 * g1 * g1 *... 
       = generator_list[0] * generator_list[1] * generator_list[1] * ...,

    then we may represent g3 as a pointer

    g3_pointer = [(0,1),(1,2),(0,2),...],

    where the first number in the tuple is the index of the generator in 
    generator_list, and the second is the multiplicative power of this
    generator, i.e. the number of elements that form an unbroken product chain.

    Note that the power of an element is defined modulo its cycle order. 
    Therefore, if the cycle orders of the generators are known, the program
    will use them to simplify pointer products and inverses.
    """

    def __init__(self, pointer, generator_list = None, generator_order = None):
        """
        Initializes a group element in the pointer representation.

        Arguments:
        pointer         - list of tuple, pointer representation of some group 
                          element;
        generator_list  - list of GroupElement_type (optional, default None),
                          if not None, provides a list of group generators;
        generator_order - list (optional, default None), if not None, provides
                          the list of generator cycle orders.
        """

        # Define the number of generators and the list of generator cycle orders
        if not_None(generator_list):
            self.n_generators = len(generator_list)
            self.order = [g.order for g in generator_list]

        else:
            if not_None(generator_order):
                self.order = generator_order
                self.n_generators = len(self.order)

            else: 
                raise Exception("Generator data not provided!")

        # Test the validity of the pointer
        self.pointer = pointer 

        for i, p in enumerate(pointer):
            if p[0] >= self.n_generators:
                raise ValueError("Pointer value {} exceeds the ".format(p[0])\
                               + "number of generators "\
                               "{}".format(self.n_generators))
            

    def __mul__(self, element):
        """
        Group element multiplication in pointer representation.
        """

        # Product of two pointers
        if isinstance(element, PointerGroupElement):
            ## Special case where self or element correspond to the identity,
            ## represented by an empty pointer [] 
            if len(self.pointer) == 0:
                return element

            elif len(element.pointer) == 0:
                return self

            else:
                ## Determine the rightmost generator of the left operator (self)
                ## and leftmost generator of the right operator (element)
                g_left  = self.pointer[-1]
                g_right = element.pointer[0]

                ## If g_left and g_right are the same, we need to increase the
                ## power of the generator (extend the generator chain)
                if g_left[0] == g_right[0]:
                    g_order = self.order[g_right[0]]
                    g_power_new = mod(g_left[1]+g_right[1], g_order)
                
                    if g_power_new == 0:
                        g_extend = []
                
                    else:
                        g_extend = [(g_right[0], g_power_new)]

                    new_pointer = self.pointer[:-1] + g_extend\
                                + element.pointer[1:]
            
                ## If g_lef and g_right are different generators, simply append
                ## the pointers
                else:
                    new_pointer = self.pointer + element.pointer

                return PointerGroupElement(new_pointer,
                                           generator_order=self.order)
            
        # (Left) product between a pointer and a tuple 
        elif isinstance(element,tuple) and len(element) == 2:
            ## Special case where self corresponds to the identity,
            ## represented by an empty pointer [] 
            if len(self.pointer) == 0:
                return PointerGroupElement([element],
                                           generator_order=self.order)

            else:
                ## Determine the rightmost generator of the left operator (self)
                g_left  = self.pointer[-1]
                g_right = element

                ## If g_left and g_right are the same, we need to increase the
                ## power of the generator (extend the generator chain)
                if g_left[0] == g_right[0]:
                    g_order = self.order[g_right[0]]
                    g_power_new = mod(g_left[1]+g_right[1], g_order)
                
                    if g_power_new == 0:
                        g_extend = []
                
                    else:
                        g_extend = [(g_right[0], g_power_new)]

                    new_pointer = self.pointer[:-1] + g_extend
            
                ## If g_lef and g_right are different generators, simply append
                ## the pointers
                else:
                    new_pointer = self.pointer + [element]

                return PointerGroupElement(new_pointer,
                                           generator_order=self.order)

        # Left multiplication by other types is not defined
        else:
            raise TypeError("Multiplication is not defined for types "\
                            "{} and {}".format(self.__class__.__name__, 
                                               type(element).__name__))


    def __rmul__(self, element):
        """
        Right group action is only defined for tuples.
        """
        # (Left) product between a pointer and a tuple 
        if isinstance(element,tuple) and len(element) == 2:
            ## Special case where self corresponds to the identity,
            ## represented by an empty pointer [] 
            if len(self.pointer) == 0:
                return PointerGroupElement([element],
                                           generator_order=self.order)

            else:
                ## Determine the leftmost generator of the right operator (self)
                g_right = self.pointer[0]
                g_left  = element

                ## If g_left and g_right are the same, we need to increase the
                ## power of the generator (extend the generator chain)
                if g_left[0] == g_right[0]:
                    g_order = self.order[g_right[0]]
                    g_power_new = mod(g_left[1]+g_right[1], g_order)
                
                    if g_power_new == 0:
                        g_extend = []
                
                    else:
                        g_extend = [(g_right[0], g_power_new)]

                    new_pointer = g_extend + self.pointer[1:]
            
                ## If g_lef and g_right are different generators, simply append
                ## the pointers
                else:
                    new_pointer = [element] + self.pointer 

                return PointerGroupElement(new_pointer,
                                           generator_order=self.order)

        # Right multiplication by other types is not defined
        else:
            raise TypeError("Multiplication is not defined for types "\
                            "{} and {}".format(type(element).__name__), 
                                               self.__class__.__name__)


    def inv(self):
        """
        Group element inverse for pointer representation.
        """
 
        pointer_inv = [(p[0],mod(-p[1],self.order[p[0]])) for p in self.pointer]

        return PointerGroupElement(pointer_inv,
                                   generator_order=self.order)
        

    def __eq__(self, element):
        """
        Pointer comparison.

        Note that a pointer representation of a group element is not unique,
        so this function is equivalent to group element comparison. 
        """

        if isinstance(element, PointerGroupElement): 
            return self.pointer == element.pointer

        else:
            warnings.warn("Comparison of " + self.__class__.__name__\
                        + " with " + type(element).__name__\
                        + " yields False by default.")
            return False


    def __str__(self):
        """
        User-friendly output.
        """

        return str(self.pointer)


    def __repr__(self):
        """
        Provedes useful print output.
        """
        cls = self.__class__.__name__
        return f"{cls}(pointer = {self.pointer!r})"


"""
-------------------------------------------------------------------------------
Matrix representation of group elements
-------------------------------------------------------------------------------
"""

class MatrixGroupElement(GroupElement):
    """
    Converts a matrix operator to a group element object with strict
    multiplication and inversion rules. 
    """

    def __init__(self, operator, operator_inv = None, cycle_order = None,
                                 store_inverse = True):
        """
        Defines the matrix operator and, optionally, its inverse.

        Arguments:
        operator         - 2darray_type, matrix operator, defining the group 
                           element;
        operator_inv     - 2darray_type, (optional, default = None), if not 
                           None, proposes an inverse of operator;
        cycle_order      - int, (optional, default = None), if not None, gives 
                           the cycle order of the operator, i.e. n for which 
                           operator^n = identity;
        store_inverse    - bool, (optional, default = True) if True, explicitly 
                           stores the matrix inverse of the operator.
        """

        # Define numerical precision for the matrix values
        eps = 1e-10
        log_eps = 10

        self.operator = np.round(np.array(operator),log_eps) 
        self.rank = len(self.operator)
        self.store_inverse = store_inverse
        self.order = cycle_order
        self.orthogonal_basis = _check_orthogonal(self.operator)

        if self.store_inverse == True:
            if not_None(operator_inv):

                # Test that the proposed inverse yields identity when multiplied
                # by self.operator
                operator_inv = np.array(operator_inv)
                identity_test = operator_inv.dot(self.operator)\
                              - np.eye(self.rank)
                
                if np.max(np.abs(identity_test)) > eps:
                    raise ValueError("Proposed inverse does not produce "\
                                     "identity under multiplication with the "\
                                     "operator!")

                self.operator_inv = MatrixGroupElement(operator_inv,
                                                         store_inverse=False)

            else:
                self.operator_inv = self.inv()

        else:
            self.operator_inv = None

    
    def __mul__(self, element):
        """
        Shortcut for calculating (left) group element action.
        """

        # Multiplication of two group elements
        if isinstance(element, MatrixGroupElement):
            
            if element.rank != self.rank:
                raise TypeError("Cannot perform multiplication between "\
                                "matrices of rank {} and {}!".format(
                                                             self.rank, 
                                                             element.rank))
            
            product = self.operator.dot(element.operator)

            return MatrixGroupElement(product,store_inverse=False)


        elif isinstance(element, np.ndarray) or isinstance(element, list):

            element = np.array(element)

            if element.shape[0] != self.rank:
                raise TypeError("Cannot perform multiplication between "\
                                "matrices of rank {} and {}!".format(
                                                             self.rank, 
                                                             element.shape[0]))
            
            return self.operator.dot(element)

        else:
            raise TypeError("Cannot multiply "\
                          + self.__class__.__name__ + " and "\
                          + type(element).__name__ + "!") 

    
    def __rmul__(self, element):
        """
        Shortcut for calculating (right) group element action.
        """

        if isinstance(element, np.ndarray) or isinstance(element, list):

            element = np.array(element)

            if element.shape[-1] != self.rank:
                raise TypeError("Cannot perform multiplication between "\
                                "matrices of rank {} and {}!".format(
                                                             element.shape[-1],
                                                             self.rank))
            
            return element.dot(self.operator)

        else:
            raise TypeError("Cannot multiply " + type(element).__name__\
                          + " and " + self.__class__.__name__ + "!") 

    
    def inv(self, store_inverse = False):
        """
        Returns matrix inverse of self.operator.

        Arguments:
        store_inverse - bool, (optional, default = False), if True, also stores
                        the original operator as the inverse of operator_inv. 
        
        Returns:
        operator_inv - MatrixGroupElement, inverse of the self.operator.
        """

        if not_None(self.operator_inv):
            return self.operator_inv

        else:
            if self.orthogonal_basis:
                operator_inverse = self.operator.T

            else:
                operator_inverse = np.linalg.inv(self.operator)

            if store_inverse == True:
                return MatrixGroupElement(operator_inverse,
                                            store_inverse = True,
                                            operator_inverse = operator)

            else:
                return MatrixGroupElement(operator_inverse,
                                            store_inverse = False)

    def __eq__(self, element):
        """
        Determines if two matrix group elements are the same up to numerical
        precision.
        """
        
        if isinstance(element, MatrixGroupElement):
            
            # Define numerical tolerance
            eps = 1e-10
            
            return np.isclose(self.operator,element.operator).all()

        else:
            warnings.warn("Comparison of " + self.__class__.__name__\
                        + " with " + type(element).__name__\
                        + " yields False by default.")
            return False

    def __str__(self):
        """
        User-friendly output of the group element.
        """

        # Define float precision for output
        log_eps = 4

        return str(np.round(self.operator, log_eps))

    def __repr__(self):
        """
        Provedes useful print output.
        """
        cls = self.__class__.__name__
        return f"{cls}(operator = {np.round(self.operator,4)!r})"


"""
-------------------------------------------------------------------------------
Frequently used supplementary functions
-------------------------------------------------------------------------------
"""

def array_in_list(a, a_list):
    """
    Determines if a np.ndarray is included in a list of np.ndarrays. 
    """
    # Define numerical precision
    eps = 1e-10 
    return any((np.isclose(a,p,eps)).all() for p in a_list)


def element_in_list(g, g_list):
    """
    Determines if a GroupElement_type is included in a list of 
    GroupElement_types. 
    """
    return any(g == p for p in g_list)


def not_None(a):
    """
    Checks if a is of NoneType, returns True if it isn't.
    """
    return not isinstance(a,type(None))


def mod(a,n):
    """
    If n is not None, return a % n, otherwise return a.
    """
    if not_None(n):
        return a % n
    else:
        return a

def _check_orthogonal(operator):
    """
    Checks if the operator is orthogonal.
    """

    operator = np.array(operator)

    # Define numerical precision required
    eps = 1e-10

    # Check if O * O.T = identity
    diff =  np.max(np.abs(operator.dot(operator.T) - np.eye(len(operator))))

    if diff < eps:
        return True
    else:
        return False
