#! /usr/bin/env python3
# Andrey Zelenskiy, 2024

"""
=================
symmetry_utils.py
=================

This script defines the `group` object, which contains all of the necessary 
information and methods for symmetry analysis.
"""

import numpy as np
import warnings

def custom_formatwarning(msg, *args, **kwargs):
    """
    When throwing a warning, only throw the message
    """
    return str(msg) + '\n'

warnings.formatwarning = custom_formatwarning


# Frequently used functions

def array_in_list(a, a_list):
    """
    Determines if a np.ndarray is included in a list of np.ndarrays. 
    """
    return any((a == p).all() for p in a_list)


def element_in_list(g, g_list):
    """
    Determines if a group_element_type is included in a list of 
    group_element_types. 
    """
    return any(g == p for p in g_list)


# Definition of the group element interface

class group_element:
    """
    Interface for an object representing an element of a symmetry group.  
    """

    def __mul__(self, element):
        """
        Left group action.
        """
        pass

    def __rmul__(self, element):
        """
        Right group action.
        """
        pass

    def inv(self):
        """
        Group element inverse.
        """
        pass

    def __eq__(self, element):
        """
        Group element comparison
        """
        pass

# Definition of the group object

class group:
    """
    A container for storing the properties and methods of a symmetry group. 
    """

    def __init__(self, generators):
        """
        Defines the group generators.
        """

        self.generators = generators


    # Routines for orbit/stabilizers calculations

    def stabilizer_generator_filter(stabilizer, stabilizer_list, blacklist):
        """
        Determines whether a stabilizing operation qualifies as a new generator
        of the stabilizer group. 
    
        Arguments:
        stabilizer      - np.2darray, stabilizer matrix;
        stabilizer_list - list of np.2darray, list of known generators of the
                          stabilizer group;
        blacklist       - list of np.2darray, list of operators related to the
                          known generators of the stabilizer group.

        Returns:
        Either the original, or the updated stabilizer_list, blacklist.
        """

        # Check if the stabilizer is already in the stabilizer list
        if not array_in_list(stabilizer, stabilizer_list):

            # Check if the stabilizer is related to the known generators
            if not array_in_list(stabilizer, blacklist):  

                # Both tests are passed, update stabilizer_list and blacklist  
                extended_stabilizer = [np.eye(3,dtype=int)] + stabilizer_list

                for s in extended_stabilizer:
                    g_head = s.dot(stabilizer)
                    g_chain = g_head
                    while not array_in_list(g_chain, blacklist):
                        blacklist += [g_chain]
                        g_chain = g_chain.dot(g_head)

                stabilizer_list += [stabilizer]

        return stabilizer_list, blacklist         

    def calculate_orbit(self, p0, as_pointer = True):
        """
        Calculates the orbit of a single point under the action of the group. 

        When a group element is applied to a point (seed), it either generates
        a new point or leaves the seed unchanged. The set of all points 
        generated by applying all group elements to the seed is called the 
        orbit of the seed point.

        The following algorithm allows one to calculate the orbit, transporters
        (group elements that transform the seed into other points in the orbit),
        and stabilizers (group elements that transform the seed into itself).

        To save memory, transporters and stabilizers may be stored as pointers
        to the sequence of generators that produce the correct group element. 
        For example, if the generator set is {g1,g2}, and element g3 transforms 
        the seed point p0 to point p1, i.e.

        g3 * p0 = p1,

        where 

        g3 = g1 * g2 * g2 
           = generators[0] * generators[1] * generators[1],

        we may represent g3 as a pointer

        g3_pointer = [0,1,1].

        The option to output group elements as pointers is controlled by 
        as_pointer argument.

        Note that the set of all stabilizers of the seed comprises a group 
        (called the stabilizer group). The list of stabilizers in the output
        of this program will contain the generators of the stabilizer group,
        but will have redundant elements (i.e. not a miniomal generating set).
        Afterwards, one can use the generator_filter routine to obtaine the 
        minimal generating set.


        Arguments:
        p0         - array_type with rank equal to the rank of the group 
                     elements, the 'seed' point of the orbit;
        as_pointer - bool, (optional, default = True), when True, outputes the
                     group elements as pointers to the generating set.

        Returns:
        output           - list, which, depending on options, contains:
        orbit            - list of np.ndarray, a closed set of points generated
                           from the seed  through application of group elements;
        transporter_dict - dict tuple:list (as_pointer = True) or 
                           dict tuple:group_element_type (as_pointer = False),
                           a set of group operators (values) that transform the
                           seed to other points in the orbit (keys);
        stabilizer_list  - list of lists (as_pointer = True) or
                           list of group_element_type (as_pointer = False),
                           operators that leave the seed point unchanged.
        """

        orbit = [point_0]

        if as_pointer:
            transporter_dict = {tuple(p0):[]}
            stabilizer_list  = [[]]

        else:
            transporter_dict = {tuple(p0):np.eye(self.rank)}
            stabilizer_list = [np.eye(self.rank)]

        for p in orbit:
            for ind_g, g in enumerate(self.generators):
                q = g*p

                if not array_in_list(q, orbit):
                    orbit += [q]

                    if as_pointer:
                        transporter_dict[tuple(q)] = \
                                transporter_dict[tuple(p)] + [ind_g]

                    else:
                        transporter_dict[tuple(q)] = \
                                g*transporter_dict[tuple(p)]

                else:
                    """
                    We assume that some group generator g satisfies

                    g_21 p_1 = p_2

                    where p and q are points in the orbit of a known seed point
                    p_0. Assuming that

                    p_1 = g_10 p_0
                    p_2 = g_20 p_0

                    where operators g_10 and g_20 are known, we can obtain two
                    stabilizer operations as

                    s_1 = g_20^-1 g_21 g_10
                    s_2 = g_10^-1 g_21^-1 g_20 = s_1^-1

                    Since we are interested in generators, we only need s_1.
                    """

                    # TODO it becomes tricky to store stabilizers as pointers, 
                    # since we must know the inverses... 
                    g_10 = transporter_dict[tuple(p)]
                    g_20 = transporter_dict[tuple(q)]
                    g_20_inv = g_20.inv()
                    stabilizer = g_20_inv*g*g_10

                    if not element_in_list(stabilizer, stabilizer_list):
                        stabilizer_list += [stabilizer]

        return orbit, transporter_dict, stabilizer_list

    def __str__(self):
        """
        Provides user-friendly summary of the group container.
        """

        generators_str = "\n".join([str(g) for g in self.generators])

        summary_string = 'Symmetry group defined by generators:\n'\
                + generators_str

        return summary_string







def as_permutation(a_list, matrix_operator):
    """
    Transforms a matrix operator into a cycle/permutation basis using a closed
    set of points.

    Arguments:
    a_list          - list of np.1darray, a set of points, which defines the
                      space of permutations;
    matrix_operator - np.2darray, a symmetry operator acting on the points in 
                      the a_list.

    Returns:
    permutation_operator - tuple of size len(a_list), permutation 
                           representation of the matrix_operator.
    """

    # Construct a hash map for the points in the a_list  
    dict_keys = [tuple(p) for p in a_list]
    dict_vals = [i for i in range(len(a_list))]
    index = dict(zip(dict_keys,dict_vals))

    try:
        permutation_operator = [index[tuple(matrix_operator.dot(p))] \
                for p in a_list]

    except KeyError:
        raise ValueError("Cannot determine the permutation representation: "\
                + "list of points is not a closed set")


        return permutation_operator
