# List of generators of the 32 crystallographic point groups

## Triclinic
[C1]
elements = ["E"]

[Ci]
elements = ["I"]


## Monoclinic
[C2]
elements = ["C2_001"]

[C1h]
elements = ["m_001"]

[C2h]
elements = ["C2_001","I"]


## Orthorhombic
[D2]
elements = ["C2_010","C2_001"]

[C2v]
elements = ["C2_001","m_010"]

[D2h]
elements = ["C2_010","C2_001","I"]


## Tetragonal
[C4]
elements = ["C4p_001"]

[S4]
elements = ["S4p_001"]

[C4h]
elements = ["C4p_001","I"]

[D4]
elements = ["C4p_001","C2_010","C2_001"]

[C4v]
elements = ["C4p_001","C2_001","m_010"]

[D2d]
elements = ["S4p_001","C2_010","C2_001"]

[D4h]
elements = ["C4p_001","C2_010","C2_001","I"]


## Trigonal
[C3]
elements = ["C3p_001"]

[C3i]
elements = ["S3p_001"]

[D3]
elements = ["C3p_001","C2_1-10"]

[C3v]
elements = ["C3p_001","m_110"]

[D3d]
elements = ["S6p_001","C2_1-10","I"]


## Hexagonal
[C6]
elements = ["C6p_001"]

[C3h]
elements = ["C3p_001","I"]

[C6h]
elements = ["C6p_001","I"]

[D6]
elements = ["C3p_001","C2_001","C2_110"]

[C6v]
elements = ["C3p_001","C2_001","m_110"]

[D3h]
elements = ["C3p_001","C2_1-10","m_001"]

[D6h]
elements = ["C3p_001","C2_001","C2_110","I"]


## Cubic
[T]
elements = ["C3p_111","C2_010","C2_001"]

[Th]
elements = ["C3p_111","C2_010","C2_001","I"]

[O]
elements = ["C3p_111","C2_010","C2_110","C2_001"]

[Td]
elements = ["C3p_111","C2_010","C2_001","m_1-10"]

[Oh]
elements = ["C3p_111","C2_010","C2_110","C2_001","I"]
