[000]
E = [ [  1,  0,  0 ], [  0,  1,  0 ], [  0,  0,  1 ] ]
I = [ [ -1,  0,  0 ], [  0, -1,  0 ], [  0,  0, -1 ] ]

[100]
C2   = [ [  1,  0,  0 ], [  0, -1,  0 ], [  0,  0, -1 ] ]
C2_H = [ [  1, -1,  0 ], [  0, -1,  0 ], [  0,  0, -1 ] ]
C4_p = [ [  1,  0,  0 ], [  0,  0,  1 ], [  0, -1,  0 ] ]
C4_m = [ [  1,  0,  0 ], [  0,  0, -1 ], [  0,  1,  0 ] ]

[010]
C2   = [ [ -1,  0,  0 ], [  0,  1,  0 ], [  0,  0, -1 ] ]
C2_H = [ [ -1,  0,  0 ], [ -1,  1,  0 ], [  0,  0, -1 ] ]
C4_p = [ [  0,  0, -1 ], [  0,  1,  0 ], [  1,  0,  0 ] ]
C4_m = [ [  0,  0,  1 ], [  0,  1,  0 ], [ -1,  0,  0 ] ]

[001]
C2     = [ [ -1,  0,  0 ], [  0, -1,  0 ], [  0,  0,  1 ] ]  
C3_p_H = [ [  0, -1,  0 ], [  1, -1,  0 ], [  0,  0,  1 ] ]
C3_m_H = [ [ -1,  1,  0 ], [ -1,  0,  0 ], [  0,  0,  1 ] ]
C4_p   = [ [  0, -1,  0 ], [  1,  0,  0 ], [  0,  0,  1 ] ]
C4_m   = [ [  0,  1,  0 ], [ -1,  0,  0 ], [  0,  0,  1 ] ]
C6_p_H = [ [  1, -1,  0 ], [  1,  0,  0 ], [  0,  0,  1 ] ]
C6_m_H = [ [  0,  1,  0 ], [ -1,  1,  0 ], [  0,  0,  1 ] ]

[110]
C2 = [ [  0,  1,  0 ], [  1,  0,  0 ], [  0,  0, -1 ] ]

[101]
C2 = [ [  0,  0,  1 ], [  0, -1,  0 ], [  1,  0,  0 ] ]

[011]
C2 = [ [ -1,  0,  0 ], [  0,  0,  1 ], [  0,  1,  0 ] ]

[1-10]
C2 = [ [  0, -1,  0 ], [ -1,  0,  0 ], [  0,  0, -1 ] ]

[-101]
C2 = [ [  0,  0, -1 ], [  0, -1,  0 ], [ -1,  0,  0 ] ]

[01-1]
C2 = [ [ -1,  0,  0 ], [  0,  0, -1 ], [  0, -1,  0 ] ]

[111]
C3_p = [ [  0,  0,  1 ], [  1,  0,  0 ], [  0,  1,  0 ] ]
C3_m = [ [  0,  1,  0 ], [  0,  0,  1 ], [  1,  0,  0 ] ]

[-111]
C3_p = [ [  0, -1,  0 ], [  0,  0,  1 ], [ -1,  0,  0 ] ]
C3_m = [ [  0,  0, -1 ], [ -1,  0,  0 ], [  0,  1,  0 ] ]

[1-11]
C3_p = [ [  0, -1,  0 ], [  0,  0, -1 ], [  0, -1,  0 ] ]
C3_m = [ [  0,  0,  1 ], [ -1,  0,  0 ], [  0,  -1,  0 ] ]

[11-1]
C3_p = [ [  0,  1,  0 ], [  0,  0, -1 ], [ -1,  0,  0 ] ]
C3_m = [ [  0,  0, -1 ], [  1,  0,  0 ], [  0, -1,  0 ] ]

[210]
C2_H = [ [  1,  0,  0 ], [  1, -1,  0 ], [  0,  0, -1 ] ] 

[120]
C2_H = [ [ -1,  1,  0 ], [  0,  1,  0 ], [  0,  0, -1 ] ] 


