#! /usr/bin/env python3
# Andrey Zelenskiy, 2024

"""
=================
group_utils.py
=================

This submodule defines the `Group` object, which contains all
of the necessary information and methods for symmetry analysis.
"""

import numpy as np

from samosa.api.api_utils import ArrayType, NoneType
from samosa.api.api_utils import is_None, not_None
from samosa.api.api_utils import check_type, check_len, check_shape
from samosa.api.api_utils import custom_format_warning

from samosa.symmetry.representations import GroupElement, IdentityGroupElement
from samosa.symmetry.representations import PointerGroupElement

import warnings
warnings.formatwarning = custom_format_warning
"""
-------------------------------------------------------------------------------
Group class
-------------------------------------------------------------------------------
"""


class Group:
    """
    A container for storing the properties and methods of a symmetry group.
    """

    def __init__(self, 
                 generators, 
                 name=None,  
                 order=None,
                 elements=None,
                 character_table=None,
                 irreps=None,
                 filter_generators=False):
        """
        Defines the basic group properties.

        Arguments:
        generators        - list of objects derrived from GroupElement class,
                            list of group generators;

        name              - str, (default=None) user-specified name of the
                            group;

        order             - int, (default=None) order of the group (number of 
                            elements);

        elements          - list of objects derrived from GroupElement class,
                            (default=None), list of group elements;

        character_table   - 2d_ArrayType, (default=None) character table of the
                            group;

        irreps            - list of ArrayType, (default=None) list of 
                            irreducible group representations;

        filter_generators - bool, (default=False) and option to perform
                            filtering of generators to remove redundant
                            operators.
        """
        # Initialize group generators
        self.__elements = None

        check_type('filter_generators', filter_generators, bool)
        if filter_generators == True:
            generators = self.generator_filter(generators)

        self.generators = generators

        # Initialize optional properties
        self.name = name
        self.order = order
        self.elements = elements
        self.character_table = character_table
        self.irreps = irreps

    def calculate_elements(self):
        """
        Calculates all group elements from the list of generators.
        """
        dim = self.generators[0].dim
        self.__elements = [IdentityGroupElement(dim=dim)]

        for e in self.__elements:
            for g in self.generators:
                new_element = g*e
                if not _element_in_list(new_element, self.__elements) and\
                   not new_element.is_identity:
                    self.__elements += [new_element]

        self.order = len(self.elements)

        return self.elements
    
    #TODO
    def calculate_classes(self):
        """
        Sorts group elements into conjugate classes.
        """
        if is_None(self.elements):
            element_list = list(self.calculate_elements())
        else:
            element_list = list(self.elements)

        self.__conjugate_classes = []
        
        for i in range(self.order):
            e = element_list[i]
            
            if e == 0:
                continue
            else:
                class_ = [e]
                element_list[i] = 0

                for h in self.elements:
                    e_h = h.inv*e*h

                    if not i in class_:
                        class_ += [i]
                        element_list[i] = 0

            self.__conjugate_classes += [class_]

        return self.conjugate_classes

    def calculate_orbit(self, p0, as_pointer=False):
        """
        Calculates the orbit of a single point under the action of the group.

        When a group element is applied to a seed point (p0), it either
        generates a new point or leaves the seed unchanged. The set of all
        points generated by applying all group elements to the seed is called
        the  orbit of the seed point.

        The following algorithm allows one to calculate the orbit, generators
        of the group, represented by permutations of the members of the orbit,
        transporters (group elements that transform the seed into other points
        in the orbit), and stabilizers (group elements that transform the seed
        into itself).

        Generators in the permutation representation are stored as a dict map
        from one point in the orbit to another (using integer hashing).

        To save memory, transporters and stabilizers may be stored as pointers
        to the sequence of generators that produce the correct group element.
        The option to output group elements as pointers is controlled by
        as_pointer argument.

        Note that the set of all stabilizers of the seed comprises a group
        (called the stabilizer group). The list of stabilizers in the output
        of this program will contain the generators of the stabilizer group,
        but will have redundant elements (i.e. not a miniomal generating set).
        Afterwards, one can use the generator_filter routine to obtaine the
        minimal generating set.


        Arguments:
        p0         - object for which multiplication GroupElement action is
                     supported, the 'seed' point of the orbit;

        as_pointer - bool, (default = False), when True, outputes the
                     group elements as pointers to the generating set.


        Returns:
        orbit            - list of type(p0), a closed set of points generated
                           from the seed  through application of group elements;

        permutations     - list of dict int:int, generators of the group
                           represented as permutations of members of the orbit;

        transporter_dict - dict tuple : PointerGroupElement (as_pointer = True)
                           or
                           dict tuple : GroupElement_type (as_pointer = False),
                           a set of group operators (values) that transform the
                           seed to other points in the orbit (keys);

        stabilizer_list  - list of PointerGroupElement (as_pointer = True) or
                           list of GroupElement_type (as_pointer = False),
                           operators that leave the seed point unchanged.
        """
        check_type("as_pointer", as_pointer, bool)

        # Initialize the orbit and orbit member index
        orbit = [p0]
        p_ind = {self.__hashed(p0) : 0}

        if as_pointer:
            eye_element = PointerGroupElement([],
                                              generator_list=self.generators)
        else:
            eye_element = IdentityGroupElement()

        permutations = [{} for i in range(len(self.generators))]
        transporter_dict = {self.__hashed(p0) : eye_element}
        stabilizer_list = [eye_element]

        for p in orbit:
            for ind_g, g in enumerate(self.generators):
                # Calculate a new point
                q = g*p

                p_h = self.__hashed(p)
                q_h = self.__hashed(q)

                # If the new point is not in the orbit, add it and update
                # generators/permutations and transporters
                if not _array_in_list(q, orbit):
                    orbit += [q]
                    p_ind[q_h] = len(orbit) - 1

                    if as_pointer:
                        transporter_dict[q_h] = \
                                (ind_g, 1)*transporter_dict[p_h]

                    else:
                        transporter_dict[q_h] = \
                                g*transporter_dict[p_h]

                # If the new point is already in the orbit, record the operation
                # as a stabilizer
                else:
                    """
                    We assume that some group generator g satisfies

                    g_21 p_1 = p_2

                    where p and q are points in the orbit of a known seed point
                    p_0. Assuming that

                    p_1 = g_10 p_0
                    p_2 = g_20 p_0

                    where operators g_10 and g_20 are known, we can obtain two
                    stabilizer operations as

                    s_1 = g_20^-1 g_21 g_10
                    s_2 = g_10^-1 g_21^-1 g_20 = s_1^-1

                    Since we are interested in generators, we only need s_1.
                    """

                    g_10 = transporter_dict[p_h]
                    g_20 = transporter_dict[q_h]
                    g_20_inv = g_20.inv

                    if as_pointer:
                        stabilizer = (g_20_inv*(ind_g, 1))*g_10
                    else:
                        stabilizer = g_20_inv*g*g_10

                    if not _element_in_list(stabilizer, stabilizer_list):
                        stabilizer_list += [stabilizer]

                permutations[ind_g][p_ind[p_h]] = p_ind[q_h]

        permutations = [PermutationGroupElement(p) for p in permutations]

        return orbit, permutations, transporter_dict, stabilizer_list

    #TODO
    def as_permutations(self, point):
        """
        Changes the basis of the group elements to permutations of the 
        members of an orbit formed from a single point.

        point - object for which multiplication GroupElement action is
                supported, seed of the orbit used for the permutation basis.

        Returns:
        None, updates group attributes to the new permutation basis.
        """
        pass

    # Method for filtering out redundant generators
    @staticmethod
    def generator_filter(generators):
        """
        Removes redundant operators from the candidate generator list.
        """

        candidate_list = []
        filtered_generators = []

        # Remove potential duplicates and identity elements
        for g in generators:
            if not _element_in_list(g, candidate_list) and not g.is_identity:
                candidate_list += [g]

        # If the list is empty after sorting, the only generator is identity
        if len(candidate_list) == 0:
            filtered_generators = [IdentityGroupElement()]

        # If only one generator is provided, no need to perform the check
        elif len(candidate_list) == 1:
            filtered_generators = candidate_list

        else:
            blacklist = [IdentityGroupElement()]

            for g in candidate_list:
                # Check if the generator is related to the known generators
                if not _element_in_list(g, blacklist):

                    # Update self.__generators and blacklist
                    extended_element = [IdentityGroupElement()]\
                                         + filtered_generators

                    for h in extended_element:
                        g_head = h*g
                        g_chain = g_head
                        while not _element_in_list(g_chain, blacklist):
                            blacklist += [g_chain]
                            g_chain = g_chain*g_head

                    filtered_generators += [g]

        return filtered_generators

    # Hashing for orbit calculation
    @staticmethod
    def __hashed(val):
        """
        If the input value is of ArrayType, changes the type to tuple, 
        otherwise returns the value itself.
        """
        if type(val) in ArrayType:
            return tuple(val)

        else:
            return val

    # Methods for property checks
    @staticmethod
    def __check_conflicts(*checks,**kwargs):
        """
        Performs conflict checks between group generators, all elements, and
        group order.

        Arguments:
        *checks    - str, instructs which checks to perform. Allowed values:
                     "number_of_elements", 
                     "generators_in_elements",
                     "group_order";
        
        **kwargs   - depending on the checks, the key-word arguments:

        generators - list of objects derrived from GroupElement class,
                     a candidate list of generators;

        elements   - list of objects derrived from GroupElement class,
                     a candidate list of group elements;

        order      - int, proposed group order.

        Returns:
        None if all checks are passed,
        Exception if at least one of the checks is failed.
        """
        # Number of generators does not exceed the number of group elements
        if "number_of_elements" in checks:
            generators = kwargs["generators"]
            elements = kwargs["elements"]
            
            if not_None(generators) and not_None(elements):
                if len(elements) < len(generators):
                    raise Exception(f"List of generators cannot be smaller "
                                    f"than the list of group generators:\n"
                                    f"|generators| = {len(generators)}, "
                                    f"|elements| = {len(elements)}.")

        # Generators are included in the list of all group elements
        if "generators_in_elements" in checks:
            generators = kwargs["generators"]
            elements = kwargs["elements"] 

            if not_None(generators) and not_None(elements):
                for g in generators:
                    if g not in elements:
                        elements_str = "\n".join([str(e) for e in elements])
                        raise Exception(f"Input conflict: generator {g} is "
                                        f"not a member of group elements list "
                                        f"{elements_str}.")

        # Group order is the same as the size of the elements list
        if "group_order" in checks:
            elements = kwargs["elements"]
            order = kwargs["order"]

            if not_None(elements) and not_None(order):
                if len(elements) != order:
                    raise Exception(f"Input conflict: group order {order} "
                                    f"does not equal to the size of group "
                                    f"elements list {len(elements)}.")

    def __check_generators(self, generators):
        """
        Performs type and conflict checks for an input list of group 
        generators.

        Arguments:
        generators - list of objects derrived from GroupElement class,
                     a candidate list of generators.

        Returns:
        None if all checks are passed,
        Exception if at least one of the checks is failed.
        """
        
        # Type checks
        check_type('generators', generators, list)

        for g in generators:
            if not issubclass(g.__class__, GroupElement):
                raise Exception("All generators must inherit from "
                                "GroupElement class.")

            if isinstance(g, PointerGroupElement):
                raise Exception("PointerGroupElement is not a valid generator "
                                "type.")

        # Non-zero length check
        if len(generators) == 0:
            raise Exception("List of generators cannot be empty.")

        # Conflict checks
        self.__check_conflicts("generators_in_elements",
                               generators=generators,
                               elements=self.elements)

    def __check_order(self, order):
        """
        Performs type and conflict checks for an input value of group order.

        Arguments:
        order      - int, proposed group order.

        Returns:
        None if all checks are passed,
        Exception if at least one of the checks is failed.
        """
        
        # Type checks
        check_type('order', order, int, NoneType)

        if not_None(order):
            # Conflict checks
            self.__check_conflicts("group_order",
                                   elements = self.elements,
                                   order = order)

    def __check_elements(self, elements):
        """
        Performs type and conflict checks for an input list of group elements.

        Arguments:
        elements   - list of objects derrived from GroupElement class,
                     a candidate list of group elements.

        Returns:
        None if all checks are passed,
        Exception if at least one of the checks is failed.
        """
        
        # Type checks
        check_type('elements', elements, list, NoneType)

        if not_None(elements):
            for e in elements:
                if not issubclass(e.__class__, GroupElement):
                    raise Exception("All group elements must inherit from "
                                    "GroupElement class.")

                if isinstance(e, PointerGroupElement):
                    raise Exception("PointerGroupElement is not a valid group "
                                    "element type.")

            # Non-zero length check
            if len(elements) == 0:
                raise Exception("List of group elements cannot be empty.")

            # Conflict checks
            self.__check_conflicts("number_of_elements",
                                   "generators_in_elements",
                                   "group_order",
                                   generators = self.generators,
                                   elements = elements,
                                   order = self.order)

    # Group properties
    @property
    def generators(self):
        """
        List of group generators.
        """
        return self.__generators

    @generators.setter
    def generators(self, val):
        self.__check_generators(val)
        self.__generators = val

    @property
    def name(self):
        """
        User-specified name of the group.
        """
        return self.__name

    @name.setter
    def name(self, val):
        check_type('name', val, str, NoneType)
        self.__name = val

    @name.deleter
    def name(self):
        self.__name = None

    @property
    def order(self):
        """
        Returns group order (number of group elements).
        """
        return self.__order

    @order.setter
    def order(self, val):
         self.__check_order(val)
         self.__order = val

    @property
    def elements(self):
        """
        Returns a list of group elements.
        """    
        return self.__elements

    @elements.setter
    def elements(self, val):
        self.__check_elements(val)
        self.__elements = val

        if not_None(val):
            self.order = len(self.elements)

    @property
    def conjugate_classes(self):
        """
        Returns partition of group elements into conjugate classes. 
        """
        return self.__conjugate_classes

    @property
    def character_table(self):
        """
        Returns group character table.
        """
        return self.__character_table

    @character_table.setter
    def character_table(self, val):
        self.__character_table = val

    @property
    def irreps(self):
        """
        Returns irreducible representations of the group.
        """
        return self.__irreps

    @irreps.setter
    def irreps(self, val):
        self.__irreps = val

    def __str__(self):
        """
        Provides user-friendly summary of the group container.
        """

        generators_str = "\n".join([str(g) for g in self.generators])

        summary_string = ""
        if not_None(self.name):
            summary_string += f"Symmetry group {self.name}\n\n"
        
        summary_string += f"Generators:\n{generators_str};"
        
        if not_None(self.order):
            summary_string += f"\n\nGroup order: {self.order};"

        if not_None(self.elements):
            summary_string += f"\n\nGroup elements: {self.elements};"

        if not_None(self.character_table):
            summary_string += f"\n\nGroup characters: {self.character_table};"
        
        if not_None(self.irreps):
            summary_string += f"\n\nIrreducible representations: {self.irreps};"

        return summary_string

    def __repr__(self):
        """
        Provedes useful print output.
        """
        cls = self.__class__.__name__
        return f"{cls}(generators = {self.generators!r})"

"""
-------------------------------------------------------------------------------
Frequently used supplementary functions
-------------------------------------------------------------------------------
"""


def _array_in_list(a, a_list):
    """
    Determines if a np.ndarray is included in a list of np.ndarrays.
    """
    # Define numerical precision
    eps = 1e-10
    return any((np.isclose(a, p, eps)).all() for p in a_list)


def _element_in_list(g, g_list):
    """
    Determines if a GroupElement_type is included in a list of
    GroupElement_types.
    """
    return any(g == p for p in g_list)
