#! /usr/bin/env python3
# Andrey Zelenskiy, 2024

"""
=================
group_utils.py
=================

This submodule defines the `Group` and GroupElement objects, which contain all
of the necessary information and methods for symmetry analysis.
"""

import numpy as np
from samosa.api.api_utils import array_type, NoneType 
from samosa.api.api_utils import check_type, check_len, check_shape
"""
-------------------------------------------------------------------------------
Group class
-------------------------------------------------------------------------------
"""
class Group:
    """
    A container for storing the properties and methods of a symmetry group. 
    """

    def __init__(self, generators, filter_generators = False):
        """
        Defines the group generators.

        Arguments:
        generators - list of GroupElement_type, list of group generators;
        filter     - bool, (optional, default = False) and option to perform
                     filtering of generators to remove redundant operators.
        """
        check_type('generators',generators,list)

        for g in generators:
            if not issubclass(g.__class__, GroupElement):
                raise Exception("All generators must inherit from GroupElement"
                                " class.")

            if isinstance(g, PointerGroupElement):
                raise Exception("PointerGroupElement is not a valid generator"
                                " type.")


        if len(generators) == 0:
            raise Exception("List of generators cannot be empty.")

        self.generators = generators

        if filter_generators == True:
            self.generator_filter()
    

    def generator_filter(self):
        """
        Removes redundant operators from the generator list. 
        """

        candidate_list = []
        
        # Remove potential duplicates and identity elements
        for g in self.generators:
            if not _element_in_list(g,candidate_list) and not g.is_identity():
                candidate_list += [g]
        
        # If the list is empty after sorting, the only generator is identity
        if len(candidate_list) == 0:
            self.generators = [IdentityGroupElement()]

        # If only one generator is provided, no need to perform the check
        elif len(candidate_list) == 1:
            self.generators = candidate_list

        else:
            self.generators = []
            blacklist = [IdentityGroupElement()]
            
            for g in candidate_list:
                # Check if the generator is related to the known generators
                if not _element_in_list(g, blacklist):  

                    # Update stabilizer_list and blacklist  
                    extended_stabilizer = [IdentityGroupElement()]\
                                         + self.generators

                    for h in extended_stabilizer:
                        g_head = h*g
                        g_chain = g_head
                        while not _element_in_list(g_chain, blacklist):
                            blacklist += [g_chain]
                            g_chain = g_chain*g_head

                    self.generators += [g]


    def calculate_orbit(self, p0, as_pointer = False):
        """
        Calculates the orbit of a single point under the action of the group. 

        When a group element is applied to a seed point (p0), it either 
        generates a new point or leaves the seed unchanged. The set of all 
        points generated by applying all group elements to the seed is called 
        the  orbit of the seed point.

        The following algorithm allows one to calculate the orbit, generators
        of the group, represented by permutations of the members of the orbit,
        transporters (group elements that transform the seed into other points
        in the orbit), and stabilizers (group elements that transform the seed
        into itself).

        Generators in the permutation representation are stored as a dict map
        from one point in the orbit to another (using integer hashing). 

        To save memory, transporters and stabilizers may be stored as pointers
        to the sequence of generators that produce the correct group element. 
        The option to output group elements as pointers is controlled by 
        as_pointer argument.

        Note that the set of all stabilizers of the seed comprises a group 
        (called the stabilizer group). The list of stabilizers in the output
        of this program will contain the generators of the stabilizer group,
        but will have redundant elements (i.e. not a miniomal generating set).
        Afterwards, one can use the generator_filter routine to obtaine the 
        minimal generating set.


        Arguments:
        p0         - array_type with rank equal to the rank of the group 
                     elements, the 'seed' point of the orbit;
        as_pointer - bool, (optional, default = False), when True, outputes the
                     group elements as pointers to the generating set.

        Returns:
        output           - list, which, depending on options, contains:
        orbit            - list of np.ndarray, a closed set of points generated
                           from the seed  through application of group elements;
        permutations     - list of dict int:int, generators of the group
                           represented as permutations of members of the orbit;
        transporter_dict - dict tuple:list (as_pointer = True) or 
                           dict tuple:GroupElement_type (as_pointer = False),
                           a set of group operators (values) that transform the
                           seed to other points in the orbit (keys);
        stabilizer_list  - list of lists (as_pointer = True) or
                           list of GroupElement_type (as_pointer = False),
                           operators that leave the seed point unchanged.
        """

        check_type("p0",p0,array_type)
        check_type("as_pointer",as_pointer,bool)

        p0 = np.array(p0)

        # Initialize the orbit and orbit member index
        orbit = [p0]
        p_ind = {tuple(p0):0}

        if as_pointer:
            eye_element = PointerGroupElement([],
                                              generator_list=self.generators)
        else:
            eye_element = IdentityGroupElement()
        
        permutations = [{} for i in range(len(self.generators))]
        transporter_dict = {tuple(p0):eye_element}
        stabilizer_list = [eye_element]

        for p in orbit:
            for ind_g, g in enumerate(self.generators):
                # Calculate a new point 
                q = g*p

                # If the new point is not in the orbit, add it and update 
                # generators/permutations and transporters
                if not _array_in_list(q, orbit):
                    orbit += [q]
                    p_ind[tuple(q)] = len(orbit) - 1

                    if as_pointer:
                        transporter_dict[tuple(q)] = \
                                (ind_g,1)*transporter_dict[tuple(p)]

                    else:
                        transporter_dict[tuple(q)] = \
                                g*transporter_dict[tuple(p)]

                # If the new point is already in the orbit, record the operation
                # as a stabilizer
                else:
                    """
                    We assume that some group generator g satisfies

                    g_21 p_1 = p_2

                    where p and q are points in the orbit of a known seed point
                    p_0. Assuming that

                    p_1 = g_10 p_0
                    p_2 = g_20 p_0

                    where operators g_10 and g_20 are known, we can obtain two
                    stabilizer operations as

                    s_1 = g_20^-1 g_21 g_10
                    s_2 = g_10^-1 g_21^-1 g_20 = s_1^-1

                    Since we are interested in generators, we only need s_1.
                    """

                    g_10 = transporter_dict[tuple(p)]
                    g_20 = transporter_dict[tuple(q)]
                    g_20_inv = g_20.inv()
                    
                    if as_pointer:
                        stabilizer = (g_20_inv*(ind_g,1))*g_10
                    else:
                        stabilizer = g_20_inv*g*g_10

                    if not _element_in_list(stabilizer, stabilizer_list):
                        stabilizer_list += [stabilizer]

                permutations[ind_g][p_ind[tuple(p)]] = p_ind[tuple(q)]

        permutations = [PermutationGroupElement(p) for p in permutations]

        return orbit, permutations, transporter_dict, stabilizer_list
    

    def __str__(self):
        """
        Provides user-friendly summary of the group container.
        """

        generators_str = "\n".join([str(g) for g in self.generators])

        summary_string = 'Symmetry group defined by generators:\n'\
                + generators_str

        return summary_string

    def __repr__(self):
        """
        Provedes useful print output.
        """
        cls = self.__class__.__name__
        return f"{cls}(generators = {self.generators!r})"


"""
-------------------------------------------------------------------------------
Interface for group elements representation
-------------------------------------------------------------------------------
"""

class GroupElement():
    """
    Interface class for a group element object.
    """

    def __mul__(self, element):
        """
        Left group element multiplication and group action.
        """
        pass

    def __rmul__(self, element):
        """
        Right group element multiplication and group action.
        """
        pass

    def inv(self):
        """
        Group element inverse.
        """
        pass 


    def is_identity(self):
        """
        Returns True if the group element represents identity
        """
        pass

    def __eq__(self, element):
        """
        Group element comparison.
        """
        pass

    def __str__(self):
        """
        User-friendly output.
        """
        pass

"""
-------------------------------------------------------------------------------
Universal identity element
-------------------------------------------------------------------------------
"""

class IdentityGroupElement(GroupElement):
    """
    An object used to represent a universal identity element. 
    """

    def __init__(self, dim = None):
        """
        If given, initializes the dimension/trace of the identity.
        """
        check_type('dim',dim,int,NoneType)
        self.dim = dim


    def __mul__(self, element):
        """
        Shortcut for calculating (left) action.
        """
        return element
   

    def __rmul__(self, element):
        """
        Shortcut for calculating (right) action.
        """
        return element
   

    def inv(self):
        """
        Returns self, since identity is its own inverse.
        """
        return self


    def is_identity(self):
        """
        Returns True.
        """
        return True


    def __eq__(self, element):
        """
        Determines if two matrix group elements are the same up to numerical
        precision.
        """
        
        if isinstance(element, IdentityGroupElement):
            return True 

        else:
            return False


    def __str__(self):
        """
        User-friendly output of the group element.
        """
        cls = self.__class__.__name__
        return cls


    def __repr__(self):
        """
        Provedes useful print output.
        """
        cls = self.__class__.__name__
        return f"{cls}"


"""
-------------------------------------------------------------------------------
Matrix representation of group elements
-------------------------------------------------------------------------------
"""

class MatrixGroupElement(GroupElement):
    """
    Representation of a group element as a matrix operator with strict
    multiplication and inversion rules. 
    """

    def __init__(self, operator, cycle_order = None, operator_inv = None):
        """
        Defines the matrix operator and, optionally, its inverse.

        Arguments:
        operator         - 2darray_type, matrix operator defining the group 
                           element or
                           IdentityGroupElement, defines an identity element;
        cycle_order      - int, (optional, default = None), if not None, gives 
                           the cycle order of the operator, i.e. n for which 
                           operator^n = identity;
        operator_inv     - 2darray_type, (optional, default = None), if not 
                           None, proposes an inverse of operator.
        """
        
        check_type('operator',operator,array_type,IdentityGroupElement)

        # Define numerical precision for the matrix values
        eps = 1e-10
        log_eps = 10

        # Define identity if IdentityGroupElement is given
        if isinstance(operator, IdentityGroupElement):
            if operator.dim == None:
                raise ValueError("Cannot initialize MatrixGroupElement from "
                                 "IdentityGroupElement with a None type value"
                                 "of dim.")

            self.rank = operator.dim
            self.operator = np.eye(self.rank)
            self.order = 1
            self.orthogonal_basis = True
            self.operator_inv = None
        
        else:
            operator = np.round(np.array(operator),log_eps) 
            self.rank = len(operator)
            
            check_shape('operator',operator,self.rank,self.rank)

            self.operator = operator 
            self.order = cycle_order
            self.orthogonal_basis = _check_orthogonal(self.operator)

        if _not_None(operator_inv) and not self.orthogonal_basis:

            check_type('operator_inv',operator_inv,array_type)

            # Test that the proposed inverse yields identity when multiplied
            # by self.operator
            operator_inv = np.array(operator_inv)
            
            check_shape('operator_inv',operator_inv,self.rank,self.rank)
            
            identity_test = operator_inv.dot(self.operator)\
                          - np.eye(self.rank)
                
            if np.max(np.abs(identity_test)) > eps:
                raise ValueError("Proposed inverse does not produce "\
                                 "identity under multiplication with the "\
                                 "operator!")

            self.operator_inv = MatrixGroupElement(operator_inv)

        else:
            self.operator_inv = None

    
    def __mul__(self, element):
        """
        Shortcut for calculating (left) group element action.
        """

        # Multiplication of two group elements
        if isinstance(element, MatrixGroupElement):
            
            if element.rank != self.rank:
                raise TypeError("Cannot perform multiplication between "\
                                "matrices of rank {} and {}!".format(
                                                             self.rank, 
                                                             element.rank))
            
            product = self.operator.dot(element.operator)

            return MatrixGroupElement(product)

        # Left action on an array
        elif isinstance(element, array_type):

            element = np.array(element)

            if element.shape[0] != self.rank:
                raise TypeError("Cannot perform multiplication between "\
                                "matrices of rank {} and {}!".format(
                                                             self.rank, 
                                                             element.shape[0]))
            
            return self.operator.dot(element)

        # Left action on Identity object
        elif isinstance(element, IdentityGroupElement):
            return self

        else:
            raise TypeError("Cannot multiply "\
                          + self.__class__.__name__ + " and "\
                          + type(element).__name__ + "!") 

    
    def __rmul__(self, element):
        """
        Shortcut for calculating (right) group element action.
        """

        # Right action on an array
        if isinstance(element, array_type):

            element = np.array(element)

            if element.shape[-1] != self.rank:
                raise TypeError("Cannot perform multiplication between "\
                                "matrices of rank {} and {}!".format(
                                                             element.shape[-1],
                                                             self.rank))
            
            return element.dot(self.operator)

        # Right action on Identity object
        elif isinstance(element, IdentityGroupElement):
            return self

        else:
            raise TypeError("Cannot multiply " + type(element).__name__\
                          + " and " + self.__class__.__name__ + "!") 

    
    def inv(self, store_inverse = False):
        """
        Returns matrix inverse of self.operator.

        Arguments:
        store_inverse - bool, (optional, default = False), if True, also stores
                        the original operator as the inverse of operator_inv. 
        
        Returns:
        operator_inv - MatrixGroupElement, inverse of the self.operator.
        """

        check_type('store_inverse',store_inverse,bool)

        # Check if operator inverse is stored
        if _not_None(self.operator_inv):
            return self.operator_inv

        else:
            # If the operator is orthogonal, return the transpose
            if self.orthogonal_basis:
                operator_inverse = self.operator.T
            # If we have to calculate matrix inverse, it's good to store it 
            # for future calculations
            else:
                operator_inverse = np.linalg.inv(self.operator)
                self.operator_inv = MatrixGroupElement(operator_inverse)

            # Return the inverse group element
            if store_inverse == True:
                return MatrixGroupElement(operator_inverse,
                                          operator_inv = operator)

            else:
                return MatrixGroupElement(operator_inverse)

                
    def is_identity(self):
        """
        Returns True if the operator corresponds to the matrix identity.
        """
        # Define numerical tolerance
        eps = 1e-10
        
        return np.isclose(self.operator,np.eye(self.rank),eps).all()

    def __eq__(self, element):
        """
        Determines if two matrix group elements are the same up to numerical
        precision.
        """
        
        # Define numerical tolerance
        eps = 1e-10
        
        # Comparison of two MatrixGroupElements
        if isinstance(element, MatrixGroupElement):
            return np.isclose(self.operator,element.operator,eps).all()

        # Comparison with IdentityGroupElement
        elif isinstance(element, IdentityGroupElement):
            return self.is_identity() 

        # Any other comparison yields False
        else:
            warnings.warn("Comparison of " + self.__class__.__name__\
                        + " with " + type(element).__name__\
                        + " yields False by default.")
            return False

    def __str__(self):
        """
        User-friendly output of the group element.
        """

        # Define float precision for output
        log_eps = 4

        return str(np.round(self.operator, log_eps))

    def __repr__(self):
        """
        Provedes useful print output.
        """
        cls = self.__class__.__name__
        return f"{cls}(operator = {np.round(self.operator,4)!r})"


"""
-------------------------------------------------------------------------------
Permutation representation of group elements
-------------------------------------------------------------------------------
"""

class PermutationGroupElement(GroupElement):
    """
    Representation of a group element object as a permutation with strict
    multiplication and inversion rules. 
    """

    def __init__(self, permutation):
        """
        Defines the permutation tuple.

        Arguments:
        permutation - array_type or dict int : int or IdentityGroupElement,
                      Permutations in the 'ordered' representation:
                      if array_type, assume map n : permutation[n];
                      if dict, assume a map n : m, where n and m are in the 
                      same (closed) set;
                      if IdentityGroupElement, return cycle (1,2,...,dim).
        """

        check_type('permutation',permutation,dict,array_type,
                                             IdentityGroupElement)

        # Define identity if IdentityGroupElement is given
        if isinstance(permutation, IdentityGroupElement):
            if permutation.dim == None:
                raise ValueError("Cannot initialize PermutationGroupElement "
                                 "from IdentityGroupElement with a None type "
                                 "value of dim.")
            
            self.dim = permutation.dim
            self.permutation = tuple(i for i in range(self.dim))
            self.order = 1
        
        elif isinstance(permutation, dict):
            self.dim = max(permutation.keys()) + 1
            try:
                self.permutation = tuple(permutation[i]\
                                         for i in range(self.dim))
            except KeyError:
                raise ValueError("Permutation dictionary is incomplete: "
                                 "{}".format(permutation))
        
        else:
            self.permutation = tuple(permutation)
            self.dim = len(permutation)

    
    def __mul__(self, element):
        """
        Shortcut for calculating (left) group element action.
        """

        # Multiplication of two group elements
        if isinstance(element, PermutationGroupElement):
            
            if element.dim != self.dim:
                raise TypeError("Cannot perform multiplication between "\
                                "permutations of dimension {} and {}!".format(
                                                                self.dim, 
                                                                element.dim))
            
            product = tuple(element.permutation[p] for p in self.permutation)

            return PermutationGroupElement(product)

        # Left action on an array
        elif isinstance(element, array_type):

            if len(element) < self.dim:
                raise Exception("Array must be of length at least {} "
                                "in order to permute its elements.".format(
                                                                    self.dim))

            new_element = np.array(element)

            for i in range(self.dim):
                new_element[i] = element[self.permutation[i]]

            if isinstance(element, np.ndarray):
                return new_element

            else:
                return type(element)(new_element)

        # Left action on int
        elif isinstance(element, int):
            if element <= self.dim:
                return self.permutation[element]
            else:
                return element

        # Left action on Identity object
        elif isinstance(element, IdentityGroupElement):
            return self

        else:
            raise TypeError("Cannot multiply "\
                          + self.__class__.__name__ + " and "\
                          + type(element).__name__ + "!") 

    
    def __rmul__(self, element):
        """
        Right permutation action is only defined for Identity.
        """
        
        # Right action on Identity object
        if isinstance(element, IdentityGroupElement):
            return self

        else:
            raise TypeError("Cannot multiply " + type(element).__name__\
                          + " and " + self.__class__.__name__ + "!") 

    
    def inv(self):
        """
        Returns inverse of self.permutation.
        """

        permutation_inverse = np.zeros(self.dim,int) 
            
        for i in range(self.dim):
            permutation_inverse[self.permutation[i]] = i

        return PermutationGroupElement(permutation_inverse)

                
    def is_identity(self):
        """
        Returns True if none of the elements are permuted.
        """
        return self.permutation == tuple(np.arange(self.dim)) 


    def __eq__(self, element):
        """
        Determines if two permutations are the same.
        """
        
        # Comparison of two PermutationGroupElements
        if isinstance(element, PermutationGroupElement):
            return self.permutation == element.permutation

        # Comparison with IdentityGroupElement
        elif isinstance(element, IdentityGroupElement):
            return self.is_identity() 

        # Any other comparison yields False
        else:
            warnings.warn("Comparison of " + self.__class__.__name__\
                        + " with " + type(element).__name__\
                        + " yields False by default.")
            return False


    def __str__(self):
        """
        User-friendly output of the group element.
        """
        return str(self.permutation)


    def __repr__(self):
        """
        Provedes useful print output.
        """
        cls = self.__class__.__name__
        return f"{cls}(permutation = {self.permutation})"


"""
-------------------------------------------------------------------------------
Generator pointer representation of group elements
-------------------------------------------------------------------------------
"""

class PointerGroupElement(GroupElement):
    """
    Translates group element properties (element multiplication, inverse) to
    pointer representation of the group elements.


    In the pointer representation a specified group element is represented 
    as a list of integers that correspond to the sequence of generators that 
    produce the specified group element. For example, if the generator set is 
    
    generator_list = {g1,g2}, 

    and some other group element g3 can be written as  

    g3 = g1 * g2 * g2 * g1 * g1 *... 
       = generator_list[0] * generator_list[1] * generator_list[1] * ...,

    then we may represent g3 as a pointer

    g3_pointer = [(0,1),(1,2),(0,2),...],

    where the first number in the tuple is the index of the generator in 
    generator_list, and the second is the multiplicative power of this
    generator, i.e. the number of elements that form an unbroken product chain.

    Note that the power of an element is defined modulo its cycle order. 
    Therefore, if the cycle orders of the generators are known, the program
    will use them to simplify pointer products and inverses.
    """

    def __init__(self, pointer, generator_list = None, generator_order = None):
        """
        Initializes a group element in the pointer representation.

        Arguments:
        pointer         - list of tuple, pointer representation of some group 
                          element;
        generator_list  - list of GroupElement_type (optional, default None),
                          if not None, provides a list of group generators;
        generator_order - list (optional, default None), if not None, provides
                          the list of generator cycle orders.
        """

        check_type('pointer',pointer,list)

        for p in pointer:
            check_type('pointer components',p,tuple)

        check_type('generators',generator_list,list,NoneType)

        if _not_None(generator_list):
            for g in generator_list:
                if not issubclass(g.__class__, GroupElement):
                    raise Exception("All generators must inherit from "
                                    "GroupElement class.")

                if isinstance(g, PointerGroupElement):
                    raise Exception("PointerGroupElement is not a valid "
                                    " generator type.")
        
        check_type('generator_order',generator_order,list,NoneType)

        if _not_None(generator_order):
            for o in generator_order:
                check_type('generator order',o,int,NoneType)

        # Define the number of generators and the list of generator cycle orders
        if _not_None(generator_list):
            self.n_generators = len(generator_list)
            self.order = [g.order for g in generator_list]

        else:
            if _not_None(generator_order):
                self.order = generator_order
                self.n_generators = len(self.order)

            else: 
                raise Exception("Generator data not provided!")

        if isinstance(pointer, IdentityGroupElement):
            self.pointer = []

        else:
            # Test the validity of the pointer
            self.pointer = pointer 

            for i, p in enumerate(pointer):
                if p[0] >= self.n_generators:
                    raise ValueError("Pointer value {} exceeds "
                                     "the number of generators ".format(p[0])\
                                   + "{}".format(self.n_generators))

            self.simplify()


    def simplify(self):
        """
        Attempts to simplify a pointer chain by contracting pointers to the 
        same generators.
        """

        if len(self.pointer) > 0:

            new_pointer = [self.pointer[0]]

            counter = 0

            for p in self.pointer[1:]:
                if counter == -1:
                    new_pointer = [p]

                else:
                    if p[0] == new_pointer[counter][0]:
                        new_power = _mod(p[1] + new_pointer[counter][1], 
                                        self.order[p[0]])
                        
                        if new_power == 0:
                            new_pointer = new_pointer[:counter]
                            counter -= 1

                        else:
                            new_pointer[counter] = (p[0],new_power)

                    else:
                        new_pointer += [p]
                        counter += 1

            self.pointer = new_pointer
            

    def __mul__(self, element):
        """
        Group element multiplication in pointer representation.
        """

        # Product of two pointers
        if isinstance(element, PointerGroupElement):
            ## Special case where self or element correspond to the identity,
            ## represented by an empty pointer [] 
            if len(self.pointer) == 0:
                return element

            elif len(element.pointer) == 0:
                return self

            else:
                ## Determine the rightmost generator of the left operator (self)
                ## and leftmost generator of the right operator (element)
                g_left  = self.pointer[-1]
                g_right = element.pointer[0]

                ## If g_left and g_right are the same, we need to increase the
                ## power of the generator (extend the generator chain)
                if g_left[0] == g_right[0]:
                    g_order = self.order[g_right[0]]
                    g_power_new = _mod(g_left[1]+g_right[1], g_order)
                
                    if g_power_new == 0:
                        g_extend = []
                
                    else:
                        g_extend = [(g_right[0], g_power_new)]

                    new_pointer = self.pointer[:-1] + g_extend\
                                + element.pointer[1:]
            
                ## If g_lef and g_right are different generators, simply append
                ## the pointers
                else:
                    new_pointer = self.pointer + element.pointer

                return PointerGroupElement(new_pointer,
                                           generator_order=self.order)
            
        # (Left) product between a pointer and a tuple 
        elif isinstance(element,tuple) and len(element) == 2:
            ## Special case where self corresponds to the identity,
            ## represented by an empty pointer [] 
            if len(self.pointer) == 0:
                return PointerGroupElement([element],
                                           generator_order=self.order)

            else:
                ## Determine the rightmost generator of the left operator (self)
                g_left  = self.pointer[-1]
                g_right = element

                ## If g_left and g_right are the same, we need to increase the
                ## power of the generator (extend the generator chain)
                if g_left[0] == g_right[0]:
                    g_order = self.order[g_right[0]]
                    g_power_new = _mod(g_left[1]+g_right[1], g_order)
                
                    if g_power_new == 0:
                        g_extend = []
                
                    else:
                        g_extend = [(g_right[0], g_power_new)]

                    new_pointer = self.pointer[:-1] + g_extend
            
                ## If g_lef and g_right are different generators, simply append
                ## the pointers
                else:
                    new_pointer = self.pointer + [element]

                return PointerGroupElement(new_pointer,
                                           generator_order=self.order)

        # Left action on Identity object
        elif isinstance(element, IdentityGroupElement):
            return self

        # Left multiplication by other types is not defined
        else:
            raise TypeError("Multiplication is not defined for types "\
                            "{} and {}".format(self.__class__.__name__, 
                                               type(element).__name__))


    def __rmul__(self, element):
        """
        Right group action is only defined for tuples.
        """
        # (Left) product between a pointer and a tuple 
        if isinstance(element,tuple) and len(element) == 2:
            ## Special case where self corresponds to the identity,
            ## represented by an empty pointer [] 
            if len(self.pointer) == 0:
                return PointerGroupElement([element],
                                           generator_order=self.order)

            else:
                ## Determine the leftmost generator of the right operator (self)
                g_right = self.pointer[0]
                g_left  = element

                ## If g_left and g_right are the same, we need to increase the
                ## power of the generator (extend the generator chain)
                if g_left[0] == g_right[0]:
                    g_order = self.order[g_right[0]]
                    g_power_new = _mod(g_left[1]+g_right[1], g_order)
                
                    if g_power_new == 0:
                        g_extend = []
                
                    else:
                        g_extend = [(g_right[0], g_power_new)]

                    new_pointer = g_extend + self.pointer[1:]
            
                ## If g_lef and g_right are different generators, simply append
                ## the pointers
                else:
                    new_pointer = [element] + self.pointer 

                return PointerGroupElement(new_pointer,
                                           generator_order=self.order)

        # Right action on Identity object
        elif isinstance(element, IdentityGroupElement):
            return self

        # Right multiplication by other types is not defined
        else:
            raise TypeError("Multiplication is not defined for types "\
                            "{} and {}".format(type(element).__name__), 
                                               self.__class__.__name__)


    def inv(self):
        """
        Group element inverse for pointer representation.
        """
 
        pointer_inv = [(p[0],_mod(-p[1],self.order[p[0]])) for p in self.pointer]

        return PointerGroupElement(pointer_inv,
                                   generator_order=self.order)
        

    def is_identity(self):
        """
        Returns True if the pointer is empty.
        """
        if len(self.pointer) == 0:
            return True
        else:
            return False


    def __eq__(self, element):
        """
        Pointer comparison.

        Note that a pointer representation of a group element is not unique,
        so this function is equivalent to group element comparison. 
        """

        # Comparison of two pointers
        if isinstance(element, PointerGroupElement): 
            return self.pointer == element.pointer

        # Comparison with IdentityGroupElement
        elif isinstance(element, IdentityGroupElement):
            return self.is_identity()

        # Any other comparison yields False
        else:
            warnings.warn("Comparison of " + self.__class__.__name__\
                        + " with " + type(element).__name__\
                        + " yields False by default.")
            return False


    def __str__(self):
        """
        User-friendly output.
        """

        return str(self.pointer)


    def __repr__(self):
        """
        Provedes useful print output.
        """
        cls = self.__class__.__name__
        return f"{cls}(pointer = {self.pointer!r})"


"""
-------------------------------------------------------------------------------
Frequently used supplementary functions
-------------------------------------------------------------------------------
"""

def _array_in_list(a, a_list):
    """
    Determines if a np.ndarray is included in a list of np.ndarrays. 
    """
    # Define numerical precision
    eps = 1e-10 
    return any((np.isclose(a,p,eps)).all() for p in a_list)


def _element_in_list(g, g_list):
    """
    Determines if a GroupElement_type is included in a list of 
    GroupElement_types. 
    """
    return any(g == p for p in g_list)


def _not_None(a):
    """
    Checks if a is of NoneType, returns True if it isn't.
    """
    return not isinstance(a,type(None))


def _mod(a,n):
    """
    If n is not None, return a % n, otherwise return a.
    """
    if _not_None(n):
        return a % n
    else:
        return a

def _check_orthogonal(operator):
    """
    Checks if the operator is orthogonal.
    """

    operator = np.array(operator)

    # Define numerical precision required
    eps = 1e-10

    # Check if O * O.T = identity
    diff =  np.max(np.abs(operator.dot(operator.T) - np.eye(len(operator))))

    if diff < eps:
        return True
    else:
        return False
